import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      // Sidebar Items
      home: "Home",
      dashboard: "Dashboard",
      // screening: "AI Screening",  <--  تم حذفه لأنه مكرر
      labs: "Labs",
      manageLabs: "Manage Labs",
      appointments: "Appointments",
      messages: "Messages",
      settings: "Settings",
      logout: "Logout",
      
      // Header Items
      welcome: "Welcome",
      search: "Search...",

      // Screening Page
      screening: {
        label: "AI Screening", // ✅ تم إضافته هنا ليستخدم في السايدبار
        title: "AI Breast Cancer Screening",
        subtitle: "A tool for early diagnosis assistance using deep learning algorithms. Enter cell measurements (FNA) for instant analysis.",
        clear: "Clear Form",
        demoData: "Fill Demo Data",
        analyze: "Analyze Data",
        analyzing: "Analyzing Tissue...",
        newScan: "New Scan",
        ready: "Ready for Analysis",
        readyDesc: "Complete the form and click Analyze below.",
        diagnosisTitle: "Predicted Diagnosis",
        confidence: "AI Confidence",
        malignant: "Malignant",
        benign: "Benign",
        malignantDesc: "Malignant Tumor (Requires immediate attention)",
        benignDesc: "Benign Tumor (Safe)",
        nextSteps: "Suggested Next Steps:",
        stepConsult: "Consult an oncologist immediately.",
        stepBiopsy: "Perform confirmatory biopsy.",
        stepFollowUp: "Periodic follow-up in 6 months.",
        stepRecord: "Save result to medical record.",
        disclaimerTitle: "Medical Disclaimer",
        disclaimerText: "These results are generated by an AI model for guidance purposes only. Do not rely on them as a final diagnosis without consulting a specialist."
      }
    }
  },
  ar: {
    translation: {
      // عناصر القائمة الجانبية
      home: "الرئيسية",
      dashboard: "لوحة التحكم",
      labs: "المعامل",
      manageLabs: "إدارة المعامل",
      appointments: "المواعيد",
      messages: "الرسائل",
      settings: "الإعدادات",
      logout: "تسجيل خروج",

      // عناصر الهيدر
      welcome: "مرحباً",
      search: "بحث...",

      // صفحة الفحص
      screening: {
        label: "الفحص الذكي", // ✅ تم إضافته هنا
        title: "الفحص الذكي للأورام",
        subtitle: "أداة مساعدة للتشخيص المبكر باستخدام خوارزميات التعلم العميق. قم بإدخال قياسات الخلايا (FNA) للحصول على تحليل فوري.",
        clear: "مسح النموذج",
        demoData: "تجربة بيانات (ورم خبيث)",
        analyze: "تحليل البيانات",
        analyzing: "جاري تحليل الأنسجة...",
        newScan: "فحص حالة جديدة",
        ready: "جاهز للتحليل",
        readyDesc: "أكمل إدخال البيانات في النموذج واضغط على زر التحليل أدناه.",
        diagnosisTitle: "التشخيص المتوقع",
        confidence: "مستوى الثقة (AI Confidence)",
        malignant: "Malignant (خبيث)",
        benign: "Benign (حميد)",
        malignantDesc: "ورم خبيث (يتطلب تدخل فوري)",
        benignDesc: "ورم حميد (آمن)",
        nextSteps: "الإجراءات المقترحة:",
        stepConsult: "مراجعة استشاري أورام فوراً.",
        stepBiopsy: "إجراء فحوصات تأكيدية (Biopsy).",
        stepFollowUp: "متابعة دورية بعد 6 أشهر.",
        stepRecord: "حفظ النتيجة في السجل الطبي.",
        disclaimerTitle: "إخلاء مسؤولية طبي",
        disclaimerText: "هذه النتائج تم توليدها بواسطة نموذج ذكاء اصطناعي للأغراض الاسترشادية فقط. لا يجب الاعتماد عليها كتشخيص نهائي دون مراجعة الطبيب المختص."
      }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "ar",
    detection: {
      order: ['localStorage', 'htmlTag'],
      caches: ['localStorage'],
    },
    interpolation: {
      escapeValue: false 
    }
  });

export default i18n;