import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      home: "Home",
      dashboard: "Dashboard",
      labs: "Labs",
      manageLabs: "Manage Labs",
      appointments: "Appointments",
      messages: "Messages",
      settings: "Settings",
      logout: "Logout",
      welcome: "Welcome",
      search: "Search...",
      header: {
        preferences: "Preferences",
        notifications: "Notifications",
        noNotifications: "No new notifications",
        markAllRead: "Mark all as read",
        new: "NEW"
      },
      messagesPage: {
        title: 'Messages',
        search: 'Search chats...',
        noChats: 'No previous conversations',
        typePlaceholder: 'Type your message...',
        startChat: 'Select a conversation to start',
        online: 'Online',
        now: 'Now'
      },
      settingsPage: {
        tabs: { general: 'Profile Settings', security: 'Security & Password', schedule: 'Work Schedule' },
        role: { doctor: 'Doctor', patient: 'Patient', admin: 'Admin' },
        labels: {
          fullName: 'Full Name',
          phone: 'Phone Number',
          address: 'Address',
          clinicAddress: 'Clinic Address',
          specialty: 'Specialty',
          email: 'Email Address',
          currentPass: 'Current Password',
          newPass: 'New Password',
          confirmPass: 'Confirm Password',
          languageSettings: 'Language Settings',
          appLanguage: 'App Language'
        },
        schedule: {
          hintTitle: 'Schedule Instructions:',
          hintDesc: 'Click on the time to select specific hours.',
          start: 'Start Time',
          end: 'End Time'
        },
        buttons: {
          saveProfile: 'Save Changes',
          updatePass: 'Update Password',
          saveSchedule: 'Save Schedule'
        },
        alerts: {
          passMismatch: '❌ New passwords do not match',
          profileSuccess: '✅ Profile saved successfully!',
          profileError: '❌ Save failed, check connection.',
          passSuccess: '✅ Password changed successfully',
          passError: '❌ Password change failed',
          scheduleSuccess: '✅ Clinic schedule updated successfully!',
          scheduleError: '❌ Failed to update schedule'
        },
        placeholders: {
          pass: '••••••••'
        }
      },
      screening: {
        label: "AI Screening",
        title: "AI Breast Cancer Screening",
        subtitle: "A tool for early diagnosis assistance using deep learning algorithms. Enter cell measurements (FNA) for instant analysis.",
        clear: "Clear Form",
        demoData: "Fill Demo Data",
        analyze: "Analyze Data",
        analyzing: "Analyzing Tissue...",
        newScan: "New Scan",
        ready: "Ready for Analysis",
        readyDesc: "Complete the form and click Analyze below.",
        diagnosisTitle: "Predicted Diagnosis",
        confidence: "AI Confidence",
        malignant: "Malignant",
        benign: "Benign",
        malignantDesc: "Malignant Tumor (Requires immediate attention)",
        benignDesc: "Benign Tumor (Safe)",
        nextSteps: "Suggested Next Steps:",
        stepConsult: "Consult an oncologist immediately.",
        stepBiopsy: "Perform confirmatory biopsy.",
        stepFollowUp: "Periodic follow-up in 6 months.",
        stepRecord: "Save result to medical record.",
        disclaimerTitle: "Medical Disclaimer",
        disclaimerText: "These results are generated by an AI model for guidance purposes only. Do not rely on them as a final diagnosis without consulting a specialist."
      },
      patientDashboard: {
        hero: {
          title: 'Find Best Doctors 🩺',
          desc: 'Book your appointment now with elite consultants in various medical specialties easily.'
        },
        list: {
          title: 'Available Doctors',
          empty: 'No doctors available at the moment.'
        },
        card: {
          defaultSpecialty: 'General Specialty',
          noAddress: 'Address not specified',
          shiftsTitle: 'Available Shifts',
          noShifts: 'No shifts available',
          more: 'Show more +',
          status: { confirmed: 'Booking Confirmed ✅', pending: 'Pending Approval' },
          btn: { chat: 'Message Doctor', book: 'Book Appointment', pending: 'Pending' }
        },
        modal: {
          title: 'Book New Appointment',
          slotsLabel: 'Available Slots',
          noSlots: 'This doctor has not set working hours yet.',
          reasonLabel: 'Visit Reason',
          reasonPlaceholder: 'Briefly describe reason for visit...',
          btnConfirm: 'Confirm Booking',
          btnSelectFirst: 'Select a slot first',
          alerts: {
            selectSlot: 'Please select a slot',
            success: 'Booking request sent successfully!',
            error: 'Booking failed, please try again'
          }
        }
      },
      labsPage: {
        title: "Medical Labs",
        subtitle: "Find nearest medical labs, compare prices, book appointments or upload prescriptions.",
        searchPlaceholder: "Search by lab name or location...",
        addLab: "Add Lab",
        edit: "Edit",
        delete: "Delete",
        hidePrices: "Hide Prices",
        showPrices: "Show Prices",
        book: "Book Appointment",
        confirmBook: "Confirm Booking",
        visitDate: "Visit Date",
        bookTitle: "Book test at {{name}}",
        noLabs: "No labs found.",
        addLabTitle: "Add New Lab",
        editLabTitle: "Edit Lab",
        labName: "Lab Name",
        labAddress: "Address",
        labPhone: "Phone",
        labRating: "Rating",
        labImage: "Image URL",
        services: "Services",
        serviceName: "Service Name",
        servicePrice: "Price (EGP)",
        addService: "Add Service",
        save: "Save",
        cancel: "Cancel",
        deleteConfirm: "Are you sure you want to delete this lab?",
        currency: "EGP"
      }
    }
  },
  ar: {
    translation: {
      home: "الرئيسية",
      dashboard: "لوحة التحكم",
      labs: "المعامل",
      manageLabs: "إدارة المعامل",
      appointments: "المواعيد",
      messages: "الرسائل",
      settings: "الإعدادات",
      logout: "تسجيل خروج",
      welcome: "مرحباً",
      search: "بحث...",
      header: {
        preferences: "التفضيلات",
        notifications: "الإشعارات",
        noNotifications: "لا توجد إشعارات جديدة",
        markAllRead: "تحديد الكل كمقروء",
        new: "جديد"
      },
      messagesPage: {
        title: 'الرسائل',
        search: 'ابحث في المحادثات...',
        noChats: 'لا توجد محادثات سابقة',
        typePlaceholder: 'اكتب رسالتك هنا...',
        startChat: 'اختر محادثة للبدء',
        online: 'متصل الآن',
        now: 'الآن'
      },
      settingsPage: {
        tabs: { general: 'البيانات الشخصية', security: 'الأمان وكلمة المرور', schedule: 'مواعيد العمل' },
        role: { doctor: 'طبيب', patient: 'مريض', admin: 'مسؤول' },
        labels: {
          fullName: 'الاسم الكامل',
          phone: 'رقم الهاتف',
          address: 'العنوان',
          clinicAddress: 'عنوان العيادة',
          specialty: 'التخصص',
          email: 'البريد الإلكتروني',
          currentPass: 'كلمة المرور الحالية',
          newPass: 'كلمة المرور الجديدة',
          confirmPass: 'تأكيد كلمة المرور',
          languageSettings: 'إعدادات اللغة',
          appLanguage: 'لغة التطبيق'
        },
        schedule: {
          hintTitle: 'تعليمات الجدول:',
          hintDesc: 'اضغط على الساعة لتحديد الوقت بدقة.',
          start: 'بداية العمل',
          end: 'نهاية العمل'
        },
        buttons: {
          saveProfile: 'حفظ التغييرات',
          updatePass: 'تحديث كلمة المرور',
          saveSchedule: 'حفظ الجدول'
        },
        alerts: {
          passMismatch: '❌ كلمة المرور الجديدة غير متطابقة',
          profileSuccess: '✅ تم حفظ البيانات بنجاح!',
          profileError: '❌ فشل الحفظ، تأكد من الاتصال.',
          passSuccess: '✅ تم تغيير كلمة المرور بنجاح',
          passError: '❌ فشل تغيير كلمة المرور',
          scheduleSuccess: '✅ تم تحديث جدول العيادة بنجاح!',
          scheduleError: '❌ فشل تحديث الجدول'
        },
        placeholders: {
          pass: '••••••••'
        }
      },
      screening: {
        label: "الفحص الذكي",
        title: "الفحص الذكي لسرطان الثدي",
        subtitle: "أداة مساعدة للتشخيص المبكر. قم بإدخال قياسات الخلايا (FNA) للحصول على تحليل فوري.",
        clear: "مسح النموذج",
        demoData: "تجربة بيانات (ورم خبيث)",
        analyze: "تحليل البيانات",
        analyzing: "جاري تحليل الأنسجة...",
        newScan: "فحص حالة جديدة",
        ready: "جاهز للتحليل",
        readyDesc: "أكمل إدخال البيانات في النموذج واضغط على زر التحليل أدناه.",
        diagnosisTitle: "التشخيص المتوقع",
        confidence: "مستوى الثقة (AI Confidence)",
        malignant: "Malignant (خبيث)",
        benign: "Benign (حميد)",
        malignantDesc: "سرطان ثدي خبيث (يتطلب تدخل فوري)",
        benignDesc: "كتلة حميدة (آمنة)",
        nextSteps: "الإجراءات المقترحة:",
        stepConsult: "مراجعة استشاري أورام فوراً.",
        stepBiopsy: "إجراء فحوصات تأكيدية (Biopsy).",
        stepFollowUp: "متابعة دورية بعد 6 أشهر.",
        stepRecord: "حفظ النتيجة في السجل الطبي.",
        disclaimerTitle: "إخلاء مسؤولية طبي",
        disclaimerText: "هذه النتائج تم توليدها بواسطة نموذج ذكاء اصطناعي للأغراض الاسترشادية فقط. لا يجب الاعتماد عليها كتشخيص نهائي دون مراجعة الطبيب المختص."
      },
      patientDashboard: {
        hero: {
          title: 'ابحث عن أفضل الأطباء 🩺',
          desc: 'احجز موعدك الآن بكل سهولة مع نخبة من الاستشاريين في مختلف التخصصات الطبية.'
        },
        list: {
          title: 'الأطباء المتاحون',
          empty: 'لا يوجد أطباء متاحين حالياً.'
        },
        card: {
          defaultSpecialty: 'تخصص عام',
          noAddress: 'العنوان غير محدد',
          shiftsTitle: 'المواعيد المتاحة',
          noShifts: 'لا توجد مواعيد متاحة',
          more: 'عرض المزيد +',
          status: { confirmed: 'تم تأكيد الحجز ✅', pending: 'بانتظار الموافقة' },
          btn: { chat: 'مراسلة الطبيب', book: 'حجز موعد', pending: 'قيد الانتظار' }
        },
        modal: {
          title: 'حجز موعد جديد',
          slotsLabel: 'المواعيد المتاحة',
          noSlots: 'هذا الطبيب لم يحدد مواعيد عمل بعد.',
          reasonLabel: 'سبب الزيارة',
          reasonPlaceholder: 'اكتب باختصار سبب الحجز...',
          btnConfirm: 'تأكيد الحجز',
          btnSelectFirst: 'اختر موعداً أولاً',
          alerts: {
            selectSlot: 'يرجى اختيار موعد',
            success: 'تم إرسال طلب الحجز بنجاح!',
            error: 'فشل الحجز، حاول مرة أخرى'
          }
        }
      },
      labsPage: {
        title: "المعامل الطبية",
        subtitle: "ابحث عن أقرب المعامل الطبية، قارن أسعار التحاليل، واحجز موعدك أو ارفع الروشتة مباشرة.",
        searchPlaceholder: "ابحث باسم المعمل أو المنطقة...",
        addLab: "إضافة معمل",
        edit: "تعديل",
        delete: "حذف",
        hidePrices: "إخفاء الأسعار",
        showPrices: "عرض قائمة الأسعار",
        book: "حجز موعد",
        confirmBook: "تأكيد الحجز",
        visitDate: "تاريخ الزيارة",
        bookTitle: "حجز تحليل في {{name}}",
        noLabs: "لا توجد معامل مطابقة.",
        addLabTitle: "إضافة معمل جديد",
        editLabTitle: "تعديل بيانات المعمل",
        labName: "اسم المعمل",
        labAddress: "العنوان",
        labPhone: "الهاتف",
        labRating: "التقييم",
        labImage: "رابط الصورة",
        services: "الخدمات / التحاليل",
        serviceName: "اسم التحليل",
        servicePrice: "السعر (ج.م)",
        addService: "إضافة خدمة",
        save: "حفظ",
        cancel: "إلغاء",
        deleteConfirm: "هل أنت متأكد من حذف هذا المعمل؟",
        currency: "ج.م"
      }
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "ar",
    detection: {
      order: ['localStorage', 'htmlTag'],
      caches: ['localStorage'],
    },
    interpolation: {
      escapeValue: false 
    }
  });

export default i18n;